-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 12:45:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `Agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agent` ;

CREATE TABLE IF NOT EXISTS `Agent` (
  `idAgent` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Agency` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `Street_Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `ZipCode` VARCHAR(45) NULL,
  PRIMARY KEY (`idAgent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customers` ;

CREATE TABLE IF NOT EXISTS `Customers` (
  `idCustomers` INT NOT NULL,
  `First_name` VARCHAR(45) NOT NULL,
  `Last_name` VARCHAR(45) NOT NULL,
  `DOB` DATE NOT NULL,
  `Driving_License_No` VARCHAR(9) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `ZipCode` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Agent` INT NOT NULL,
  PRIMARY KEY (`idCustomers`),
  INDEX `fk_Customers_Agent1_idx` (`Agent` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Agent1`
    FOREIGN KEY (`Agent`)
    REFERENCES `Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fueling Option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fueling Option` ;

CREATE TABLE IF NOT EXISTS `Fueling Option` (
  `idFueling Option` VARCHAR(45) NOT NULL,
  `TypeOfOption` VARCHAR(45) NULL,
  PRIMARY KEY (`idFueling Option`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Insurance` ;

CREATE TABLE IF NOT EXISTS `Insurance` (
  `idInsurance` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Price` DECIMAL(2) NULL,
  PRIMARY KEY (`idInsurance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Invoice` ;

CREATE TABLE IF NOT EXISTS `Invoice` (
  `idInvoice` VARCHAR(45) NOT NULL,
  `Rental_Price` DECIMAL(5,2) NULL,
  `Service_Tax` DECIMAL(4,2) NULL,
  `idReservation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInvoice`, `idReservation`),
  INDEX `fk_Invoice_Reservation1_idx` (`idReservation` ASC) VISIBLE,
  CONSTRAINT `fk_Invoice_Reservation1`
    FOREIGN KEY (`idReservation`)
    REFERENCES `Reservation` (`idReservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Location` ;

CREATE TABLE IF NOT EXISTS `Location` (
  `idLocation` INT NOT NULL,
  `Street_Address` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NULL,
  `ZipCode` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(12) NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Promotion` ;

CREATE TABLE IF NOT EXISTS `Promotion` (
  `idPromotion` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Discount` INT NULL,
  `Description` VARCHAR(45) NULL,
  `ID_Reservation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPromotion`),
  INDEX `fk_Promotion_Reservation1_idx` (`ID_Reservation` ASC) VISIBLE,
  CONSTRAINT `fk_Promotion_Reservation1`
    FOREIGN KEY (`ID_Reservation`)
    REFERENCES `Reservation` (`idReservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reservation` ;

CREATE TABLE IF NOT EXISTS `Reservation` (
  `idReservation` VARCHAR(45) NOT NULL,
  `Vehicle_ID` VARCHAR(45) NOT NULL,
  `ID_Customers` INT NOT NULL,
  `DropOff_IDLocation` INT NOT NULL,
  `Pickup_IDLocation` INT NOT NULL,
  `Insurance_ID` INT NOT NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `Agent` INT NOT NULL,
  INDEX `fk_Reservation_Location1_idx` (`Pickup_IDLocation` ASC) VISIBLE,
  INDEX `fk_Reservation_Customers1_idx` (`ID_Customers` ASC) VISIBLE,
  PRIMARY KEY (`idReservation`),
  INDEX `fk_Reservation_Insurance1_idx` (`Insurance_ID` ASC) VISIBLE,
  INDEX `fk_Reservation_Location2_idx` (`DropOff_IDLocation` ASC) VISIBLE,
  INDEX `fk_Reservation_Agent1_idx` (`Agent` ASC) VISIBLE,
  UNIQUE INDEX `Start_Date_UNIQUE` (`Start_Date` ASC) VISIBLE,
  UNIQUE INDEX `End_Date_UNIQUE` (`End_Date` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Vehicles1`
    FOREIGN KEY (`Vehicle_ID`)
    REFERENCES `Vehicles` (`Vehicle_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Location1`
    FOREIGN KEY (`Pickup_IDLocation`)
    REFERENCES `Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Customers1`
    FOREIGN KEY (`ID_Customers`)
    REFERENCES `Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Insurance1`
    FOREIGN KEY (`Insurance_ID`)
    REFERENCES `Insurance` (`idInsurance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Location2`
    FOREIGN KEY (`DropOff_IDLocation`)
    REFERENCES `Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Agent1`
    FOREIGN KEY (`Agent`)
    REFERENCES `Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vehicle_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vehicle_Category` ;

CREATE TABLE IF NOT EXISTS `Vehicle_Category` (
  `idCategory` VARCHAR(45) NOT NULL,
  `categoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vehicles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vehicles` ;

CREATE TABLE IF NOT EXISTS `Vehicles` (
  `Vehicle_ID` VARCHAR(45) NOT NULL,
  `idCategory` INT NOT NULL,
  `Brand` VARCHAR(45) NULL,
  `Model` VARCHAR(45) NULL,
  `Year_Model` YEAR(4) NULL,
  `Mileage` INT NULL,
  `Car_Color` VARCHAR(45) NULL,
  `idFueling Option` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Vehicle_ID`, `idCategory`, `idFueling Option`),
  INDEX `fk_Vehicles_Category_idx` (`idCategory` ASC) VISIBLE,
  INDEX `fk_Vehicles_Fueling Option1_idx` (`idFueling Option` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicles_Category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `Vehicle_Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicles_Fueling Option1`
    FOREIGN KEY (`idFueling Option`)
    REFERENCES `Fueling Option` (`idFueling Option`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
